### ISSUE TITLE
localstack

### ISSUE THREAD

**Issue by henrym6003** [mewa/terraform-aws-apigateway-cors#4]
Has anyone tried deploying this to localstack?  Im getting the below

```
{"message": "API Gateway integration type \"MOCK\" for method \"OPTIONS\" not yet implemented"}
```

Ive seen this, but it's not really helpful:  https://github.com/localstack/localstack/issues/399

**Comment by mewa** [comment]
Hi @henrym6003,

this is something that should be implemented within localstack. It would be best to raise an issue there.
