### ISSUE TITLE
Invalid argument name when running terraform init

### ISSUE THREAD

**Issue by sorin-costea** [mewa/terraform-aws-apigateway-cors#5]
```
Error: Invalid argument name
  on .terraform\modules\example_cors\main.tf line 14, in resource "aws_api_gateway_integration" "cors_integration":      
  14: "application/json" = <<EOF
Argument names must not be quoted.
```

**Comment by mewa** [comment]
Hi @sorin-costea, could you please paste the output of `terraform version`?

**Comment by blackheaven** [comment]
I have had the same error: you copy-pasted the README example, instead of the "Provision instructions" in the top right corner.

**Comment by sorin-costea** [comment]
Indeed, the readme says 1.0.0 but the latest version is 2.0.0... @mewa could you please update the readme too?
